### ISSUE TITLE
Serial Number': [Serial Number] characteristic must have a length of more than 1 character otherwise  HomeKit will reject this accessory, ignoring new value.

### ISSUE THREAD

**Issue by Ademarchis** [vectronic/homebridge-nut#10]
I have this error in my Homebridge log:
Serial Number': [Serial Number] characteristic must have a length of more than 1 character otherwise         HomeKit will reject this accessory, ignoring new value. Is possible resolve the error?

**Comment by vectronic** [comment]
Yes - I should be able to fix that. Give me a week or so...

**Comment by Ademarchis** [comment]
Ok Thank you, I wait your news.

Alessandro

**Comment by vectronic** [comment]
Try v2.4.4 - I am checking for empty strings on some of the characteristic values now...

**Comment by Ademarchis** [comment]
thank you very much now it's correct! Can I ask you if there is the possibility of expressing some more data? such as the internal temperature of the ups, battery life, ups status, etc? the data in question are already present in the nut and it would be sufficient to expose them if possible.

if you need to do some tests I am available.

Alessandro

**Comment by vectronic** [comment]
You should already be getting these details in homekit. See the logic here:

https://github.com/vectronic/homebridge-nut/blob/master/src/platform.ts#L159

and a screenshot here:

![F46603F8-A56B-40E3-A58F-7ADF0622B51B](https://user-images.githubusercontent.com/32313864/158139216-bd54f3b5-ecbd-4ea3-a8f5-8664cc0fedfd.png)

if you think you should be seeing temperature (my ups does not provide it) check that you actually get it from nut client first and maybe send me debug logs from homebridge.

**Comment by vectronic** [comment]
Closing this. Open another one for anything else.
