### ISSUE TITLE
nutError(Error: read ECONNRESET)

### ISSUE THREAD

**Issue by GraemeHalls** [vectronic/homebridge-nut#12]
I have apcupsd running on my Raspberry Pi connected to my APC BX950UI by USB, which is the same Pi as Homebrige is running on. I have configured the NIS under apcupsd, but I get nutError(Error: read ECONNRESET) when Homebridge tries to connect to the NUT. APCUPS NIS is configured as such:
NETSERVER on
NISIP 127.0.0.1
NISPORT 3551

I have tried many different variations of '127.0.0.1' and localhost and its internal IP address, and with/without the username/password but to no avail. 

Please can you advise?

**Comment by vectronic** [comment]
If I understand correctly you are using apcupsd? http://www.apcupsd.org

This plugin is written to work with NUT only. https://networkupstools.org

**Comment by vectronic** [comment]
Closing as no reply
