### ISSUE TITLE
Just updated to Node v18.12.1 and now I get ECONNREFUSED ::1:3943

### ISSUE THREAD

**Issue by thehauntedmattress** [vectronic/homebridge-nut#14]
I can't be for certain that Node v18.12.1 is the cause of the issue, but I did have an issue with another plugin after I updated to it (the developer has since updated that plugin and therefore it is not longer an issue).  I was wondering if maybe this plugin could be updated to support the new version of Node?  Thanks.

![Screenshot 2022-11-24 at 11 19 29 AM](https://user-images.githubusercontent.com/7905480/203829946-1531875f-43d1-4ed5-93d0-d9b031a1c9f8.png)

**Comment by vectronic** [comment]
Not entirely sure this is a plugin issue... possibly more a NUT server or the client library issue not supporting IPV6.

I assume in your plugin config you have `localhost`, try changing this to `127.0.0.1` to force IPV4 and see how it goes.

**Comment by thehauntedmattress** [comment]
Just saw this and your solution apparently worked.  Thank you!
