### ISSUE TITLE
Add Username and Password Support

### ISSUE THREAD

**Issue by jtrahan** [vectronic/homebridge-nut#6]
It looks like there is no username/password support.

**Comment by vectronic** [comment]
I have added 'experimental' support for username and password based on the docs here: https://www.npmjs.com/package/node-nut

Two caveats:

* I don't have username and password setup on my UPS, so I can't really test it.
* There isn't much documentation from node-nut on exactly how it should be used.

Could you install the latest version (2.2.0) either via the homebridge config UI or command line:

`npm install -g @vectronic/homebridge-nut`

and let me know how it goes....

Any issues, it would be best to submit debug logs from homebridge. Something like:

`homebridge -D | grep Nut`

**Comment by bubez81** [comment]
now it seems to work for me! Thank you!

[9/22/2021, 1:43:00 PM] [Ups Ufficio Soci] starting nut client for 192.168.0.2:3493
[9/22/2021, 1:43:00 PM] [Ups Ufficio Soci] nut client connected, reported devices: ApcUps=Description unavailable
[9/22/2021, 1:43:50 PM] [Ups Ufficio Soci] adding new accessory: ApcUps

**Comment by jtrahan** [comment]
2.2.0 is working. However with 2.2.1 I'm getting this error in the logs.

[9/22/2021, 12:37:27 PM] [Nut] error invoking GetUPSList on nut client: Cannot read property 'then' of undefined

**Comment by vectronic** [comment]
Sorry about that. Confusion with Node callbacks and promises.... Try 2.2.2

I actually did a quick test this time :-) and it seemed to work for me....

**Comment by jtrahan** [comment]
Much Better :) Thank you for adding it.
