### ISSUE TITLE
Possibility to exclude ups from same ip

### ISSUE THREAD

**Issue by bubez81** [vectronic/homebridge-nut#7]
Hello I have a problem.
The WD My Cloud Ex2 displays all possible connected ups on the network indiscriminately, without worrying whether they are connected or not. This generates the error:
`[11/3/2021, 8:32:59 AM] [Ellipse Pro 1600] error invoking GetUPSVars on nut client for device bcmxcp=bcmxcp: undefined
[11/3/2021, 8:32:59 AM] [Ellipse Pro 1600] error invoking GetUPSVars on nut client for device megatec=megatec: undefined
[11/3/2021, 8:32:59 AM] [Ellipse Pro 1600] error invoking GetUPSVars on nut client for device tripplite=tripplite: undefined`

Could there be an option to exclude them so that these errors do not occur?

**Comment by vectronic** [comment]
Could you try using uspc to see what response it returns when you run `uspc -L <your WD>`

https://networkupstools.org/docs/man/upsc.html

From what I can see here (section 9.5):

https://networkupstools.org/docs/developer-guide.chunked/ar01s09.html

the description should be `Unavailable` for these UPSs, if so, I can then filter on this...

**Comment by bubez81** [comment]
` michele@perlhof  /usr/local/sbin  upsc -L 192.168.1.60
usbhid: Description unavailable
bcmxcp: Description unavailable
megatec: Description unavailable
tripplite: Description unavailable
`
it's unavailable the right one too (usbhid)

**Comment by vectronic** [comment]
So just to clarify, you have them configured in your "WD My Cloud Ex2" but they are not available on the network? 

Are they sometimes available? If not, then why have them configured?

I am struggling to understand the scenario and therefore reticent to include a UPS device key blacklist into the plugin's config.

**Comment by bubez81** [comment]
no, I think the wd will automatically configure them even if I don't have them and make them available on the network, I only have the usbhid.
I cannot change the configuration in the WD unfortunately, I can only exclude them from reading the data

**Comment by vectronic** [comment]
Ok. Give me a week or so and I will come up with an optional config.

**Comment by bubez81** [comment]
you are the best! Thank you very much

**Comment by vectronic** [comment]
Hi there, I have published a new version with a new "Ups Key Excludes" config property which is an array of strings.  Hopefully this lets you filter out the unwanted entries from the Nut client response!

**Comment by bubez81** [comment]
Thank you! But what do you mean by ups key? by inserting
`ps_key_excludes": [
                "bcmxcp",
                "megatec",
                "tripplite"
            ],`
Unfortunately nothing changes I always receive:
`[11/6/2021, 10:34:40 PM] [Ellipse Pro 1600] error invoking GetUPSVars on nut client for device bcmxcp=bcmxcp: undefined
[11/6/2021, 10:34:40 PM] [Ellipse Pro 1600] error invoking GetUPSVars on nut client for device megatec=megatec: undefined
[11/6/2021, 10:34:40 PM] [Ellipse Pro 1600] error invoking GetUPSVars on nut client for device tripplite=tripplite: undefined`

**Comment by vectronic** [comment]
You understood correctly. Maybe I should test my code more 🙄I’ll get back to you.

**Comment by vectronic** [comment]
Ok - try 2.3.1

**Comment by bubez81** [comment]
wow it seems to work perfectly!
Thank you very much!!!
