### ISSUE TITLE
Invalid characteristics for accessory

### ISSUE THREAD

**Issue by hdmvide** [vectronic/homebridge-nut#8]
The accessory is correctly identified as a contact sensor on Homekit, but when I try to create an automation that detects the status of the "contact sensor", the selectable characteristic is only "temperature" instead of "opened" or " closed".

**Comment by vectronic** [comment]
Hmm that is weird. This is what I see when I start creating an Automation which is ‘A sensor detects something’ and then choose the UPS accessory:

![D1167D02-3694-43CA-BD75-AB2154178753](https://user-images.githubusercontent.com/32313864/147852539-381b9185-d91a-42a6-b46a-a40b8fb37c6c.png)

This is what see when looking at the details for the accessory:

![C1CF2930-EC7B-4087-888B-CD924BA21F4C](https://user-images.githubusercontent.com/32313864/147852560-2732a541-cff1-41b9-87a4-a020396f8588.png)


Do you see something different?

**Comment by hdmvide** [comment]
I have tried removing and adding the accessory from the configuration file and restarting Homebridge several times, and after several attempts Homebridge has associated the correct characteristic for the contact sensor accessory

I don't understand if there is a bug in Hombridge when it loads multiple characteristics for accessories, or if it's a plugin bug.

**Comment by vectronic** [comment]
@hdmvide can you tell me if your UPS accessory provides a temperature reading? My UPS doesn’t do there is a possibility it is an issue in the plug-in code which only manifests if the UPS supports retiring temp information.

**Comment by AndySwitcher** [comment]
I have the Ippon Back Basic UPS and I have same issue. This UPS provides the temperature. I think, it’s a fake parameter, because it show 25C only:

> ups.productid: 5161
> ups.status: OL
> ups.temperature: 25.0
> ups.type: offline / line interactive
> ups.vendorid: 0665 

![1F1DABAA-2BBE-4BBA-80A8-4047FBE5D0A5](https://user-images.githubusercontent.com/40441501/151678903-eb322b52-8e6e-4768-a239-554bb1bdeec9.jpeg)

**Comment by vectronic** [comment]
On the weekend I will try to move the temperature characteristic away from the contactsensor service definition and onto a new temperaturesensor service. If this doesn't help, I will just remove it entirely....

**Comment by vectronic** [comment]
Made changes and removed CurrentTemperature Characteristic. @AndySwitcher see if it works for you. @vectronic/homebridge-nut v2.4.1

You might need to remove homebridge-nut from Homebridge config, restart Homebridge, add homebridge-nut again and restart Homebridge again.
